//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SIG.rc
//
#define IDC_SHOWD2                      3
#define IDC_KILLD2                      4
#define IDC_VIEWFILE                    5
#define IDC_SELFILE                     6
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SIG_DIALOG                  102
#define ID_TMR_MAIN                     102
#define ID_TMR_CHECKSTATS               103
#define ID_TMR_FLASH                    105
#define ID_TMR_HEARTBEAT                106
#define ID_TMR_PACKETSRCV               107
#define ID_TMR_PACKETSSND               108
#define ID_TMR_ANTIIDLE                 109
#define ID_TMR_PLAYERMOVING             110
#define ID_TMR_FORCED2ONTOP             112
#define ID_TMR_APPTIME                  115
#define ID_TMR_AUTOCLOSE                116
#define ID_TMR_INGAMETIME               117
#define ID_TMR_STARTTIME                118
#define ID_TMR_STATISTICS               119
#define ID_TMR_D2JSPEVENTS              120
#define ID_TMR_PLAYER                   121
#define IDR_MAINFRAME                   128
#define IDD_PAGE_GENERAL                129
#define IDD_PAGE_LOGIN                  130
#define IDD_PAGE_CREATE                 131
#define IDD_PAGE_DELAYS                 132
#define IDR_POPUP                       153
#define IDI_BROWSE                      154
#define IDI_START_ACTIVATE              174
#define IDI_START_DEACTIVATE            175
#define IDI_STOP_ACTIVATE               176
#define IDI_STOP_DEACTIVATE             177
#define IDI_PAUSE_ACTIVATE              178
#define IDI_PAUSE_DEACTIVATE            179
#define IDI_EXIT_DEACTIVATE             180
#define IDI_EXIT_ACTIVATE               181
#define IDI_SETTINGS_ACTIVATE           182
#define IDI_SETTINGS_DEACTIVATE         183
#define IDD_PAGE_HACKS                  190
#define IDI_YES                         192
#define IDI_NO                          193
#define IDR_FILE                        195
#define IDR_HELP                        196
#define IDD_PAGE_D2JSP                  197
#define IDI_UP                          198
#define IDI_DOWN                        199
#define IDI_LIGHT_LC_GRAY               200
#define IDI_LIGHT_HB_GRAY               201
#define IDI_LIGHT_RV_GRAY               202
#define IDI_LIGHT_ST_GRAY               203
#define IDI_LIGHT_AI_GRAY               204
#define IDI_LIGHT_LC_YELLOW             205
#define IDI_LIGHT_LC_GREEN              206
#define IDI_LIGHT_LC_RED                207
#define IDI_LIGHT_HB_RED                208
#define IDI_LIGHT_RV_GREEN              209
#define IDI_LIGHT_ST_GREEN              210
#define IDI_LIGHT_AI_RED                211
#define IDD_PAGE_MULE                   212
#define IDD_DLG_ACCOUNT                 213
#define IDI_MULEMODE_DEACTIVATE         215
#define IDI_MULEMODE_ACTIVATE           216
#define IDI_MULEMODE_CHECKED            217
#define IDD_EXIT_DLG                    218
#define IDI_SHOWD2_DEACTIVATE           219
#define IDI_SHOWD2_ACTIVATE             220
#define IDD_DICEDITDLG                  221
#define IDD_DESCDLG                     223
#define IDI_QUESTIONMARK                224
#define IDI_EDITDIC                     225
#define IDI_REMOVE                      226
#define IDI_NEW                         227
#define IDR_STATISTICS                  228
#define IDI_KILLD2_ACTIVATE             229
#define IDI_KILLD2_DEACTIVATE           230
#define IDB_BKGND                       231
#define IDD_STATISTICSDLG               234
#define IDI_SELFILE_ACTIVATE            235
#define IDI_SELFILE_DEACTIVATE          236
#define IDI_VIEWFILE_ACTIVATE           237
#define IDI_VIEWFILE_DEACTIVATE         238
#define IDR_SHOWD2                      239
#define IDD_STATSDLG                    240
#define IDC_LABEL                       1001
#define IDC_APPNAME                     1002
#define IDC_APPVER                      1003
#define IDC_START                       1004
#define IDC_STOP                        1005
#define IDC_ACCOUNT                     1005
#define IDC_SETTINGS                    1006
#define IDC_PASSWORD                    1006
#define IDC_BROWSE                      1006
#define IDC_REPEATPASSWORD              1007
#define IDC_D2JSP                       1007
#define IDC_D2EXE                       1009
#define IDC_LAUNCHDELAY                 1010
#define IDC_LOGINDELAY                  1011
#define IDC_CHARSELDELAY                1012
#define IDC_JOINDELAY                   1013
#define IDC_CREATEDELAYMIN              1014
#define IDC_RADIO1                      1015
#define IDC_ERRORDELAY                  1015
#define IDC_RADIO2                      1016
#define IDC_CREATEBTNDELAY              1016
#define IDC_RADIO3                      1017
#define IDC_MINCONN                     1017
#define IDC_CHANNELNAME                 1018
#define IDC_RADIO4                      1018
#define IDC_CREATEDELAYMAX              1018
#define IDC_MESSAGE                     1019
#define IDC_PREFIX                      1020
#define IDC_MINPWDLEN                   1021
#define IDC_MAXPWDLEN                   1022
#define IDC_RADIO9                      1023
#define IDC_FILE                        1024
#define IDC_RETRY                       1024
#define IDC_MENUHELP                    1025
#define IDC_STATISTICS                  1026
#define IDC_PACKETSRCV                  1036
#define IDC_HEARTBEAT                   1037
#define IDC_REALMS                      1037
#define IDC_ANTIIDLE                    1038
#define IDC_REALMEDIT                   1038
#define IDC_PACKETSSND                  1039
#define IDC_REALMREFRESH                1039
#define IDC_LIST1                       1039
#define IDC_INGAMELIMIT                 1039
#define IDC_LOCATION                    1040
#define IDC_CHAR1                       1053
#define IDC_CHAR2                       1054
#define IDC_CHAR3                       1055
#define IDC_CLASSNAME                   1055
#define IDC_CHAR4                       1056
#define IDC_CHAR5                       1057
#define IDC_CHAR6                       1058
#define IDC_CHAR7                       1059
#define IDC_CHAR8                       1060
#define IDC_BNETIP                      1061
#define IDC_PREFERRED                   1062
#define IDC_ABIN                        1062
#define IDC_HOMEPAGE                    1063
#define IDC_AUTOLOAD                    1065
#define IDC_MANUALLOAD                  1066
#define IDC_DEFAULT                     1068
#define IDC_ADD                         1071
#define IDC_EDIT                        1072
#define IDC_CHARCOUNT                   1072
#define IDC_REMOVE                      1073
#define IDC_MULEMODE                    1073
#define IDC_CLOSEGUI                    1074
#define IDC_CLOSED2                     1075
#define IDC_USINGD2JSP                  1076
#define IDC_AUTOSTART                   1076
#define IDC_NAMETYPE                    1077
#define IDC_RADIO5                      1078
#define IDC_RADIO6                      1079
#define IDC_DIC                         1080
#define IDC_EDIT1                       1081
#define IDC_RES800                      1084
#define IDC_LQ                          1085
#define IDC_NS                          1086
#define IDC_LOCALE                      1087
#define IDC_NOPLUGIN                    1090
#define IDC_MPQ                         1091
#define IDC_LOCALETYPE                  1092
#define IDC_MPGFILE                     1093
#define IDC_MULECHARSTAYLENGTH          1094
#define IDC_PDIR                        1094
#define IDC_PDIRPATH                    1095
#define IDC_INGAMELIMITLENGTH           1096
#define IDC_CONTENTS                    1098
#define IDC_HELPMAXWAIT                 1099
#define IDC_HEAD                        1100
#define IDC_HELPABSWAIT                 1100
#define IDC_MOVEUP                      1101
#define IDC_MOVEDOWN                    1102
#define IDC_LBLENDTIME                  1102
#define IDC_STARTTIME                   1103
#define IDC_ENDTIME                     1104
#define IDC_TOTALTIME                   1105
#define IDC_CREATE_SUCCESS              1115
#define IDC_CREATE_TOT                  1116
#define IDC_INGAME_MAX                  1118
#define IDC_INGAME_MIN                  1119
#define IDC_INGAME_AVG                  1120
#define IDC_CRASH_COUNT                 1121
#define IDC_INGAME_CUR                  1122
#define IDC_DATETIMEPICKER1             1123
#define IDC_TOTALINGAMETIME             1123
#define IDC_DATETIMEPICKER2             1124
#define IDC_SHUTDOWNWINDOWS             1126
#define IDC_AUTOCLOSE_BYDATE            1127
#define IDC_AUTOCLOSE_BYLEN             1128
#define IDC_AUTOCLOSELEN                1129
#define IDC_AUTOCLOSE_NONE              1130
#define IDC_VER                         1132
#define IDC_DUMMY                       1133
#define IDC_USED2JSP                    1134
#define IDC_HPMANABAR                   1135
#define IDC_FIXEDPWD                    1140
#define IDC_USEFIXPWD                   1141
#define IDC_RADIO10                     1142
#define IDC_LBL                         1148
#define ID_HELP_HELP                    32771
#define ID_HELP_ABOUT                   32772
#define ID_POPUP_RESTORE                32773
#define ID_POPUP_ACTIVATE               32774
#define ID_STATISTICS_VIEWLOG           32775
#define ID_STATISTICS_VIEWDATA          32776
#define ID_POPUP_STARTPAUSERESUME       32780
#define ID_POPUP_STOP                   32781
#define ID_POPUP_KILLD2                 32782
#define ID_SHOWD2_ACTIVE                32786
#define ID_SHOWD2_BKGND                 32787

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        241
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1149
#define _APS_NEXT_SYMED_VALUE           122
#endif
#endif
